Add missing variable.
Fixes a client side error:

  Error: QWeb2 - template['collaboration_widget']: Runtime Error:
  ReferenceError: _t is not defined