Load security first so that view may reference it.
This fixes an issue installing this addon in a clean DB:

   ParseError: "External ID not found in the system:
   xopgi_object_merger.group_merger_manager" while parsing
   /home/manu/src/merchise/pgi/xopgi.base/xopgi/xopgi_object_merger/view/res_config_view.xml:167